apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k7w4or8br-go 
  janus-idp.io/tekton: k7w4or8br-go
  backstage.io/kubernetes-id: k7w4or8br-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k7w4or8br-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  