apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: k7w4or8br-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k7w4or8br-go 
  name: k7w4or8br-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: k7w4or8br-go 
